---
swagger: "2.0"
info:
  description: Harmony Core Sample API
  version: 1.0.0
  title: Harmony Core Sample API
  termsOfService: http://some.url
schemes:
- https
consumes:
- application/json
produces:
- application/json
paths:
  /Customers:
    get:
      description: Get all Customers
      parameters: []
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Customer'
  /Orders:
    get:
      description: Get all Orders
      parameters: []
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Order'
  /Plants:
    get:
      description: Get all Plants
      parameters: []
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Plant'
  /Vendors:
    get:
      description: Get all Vendors
      parameters: []
      responses:
        200:
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Vendor'
definitions:
  Customer:
    required:
    - CustKey
    properties:
      CustKey:
        type: integer
        example: 123
        description: Customer id
      CustRtype:
        type: integer
        example: 123
        description: Record Tag Field
      CustName:
        type: string
        example: "ABC"
        description: Customer Name
      CustStreet:
        type: string
        example: "ABC"
        description: Street Address
      CustCity:
        type: string
        example: "ABC"
        description: City
      CustState:
        type: string
        example: "ABC"
        description: State
      CustZip:
        type: integer
        example: 123
        description: Zip code
      CustContact:
        type: string
        example: "ABC"
        description: Contact
      CustPhone:
        type: integer
        example: 123
        description: Phone number
      CustFax:
        type: integer
        example: 123
        description: FAX number
      CustGift:
        type: integer
        example: 123
        description: Customer Premium Gift
      CustTcode:
        type: string
        example: "ABC"
        description: Terms code
      CustTaxno:
        type: integer
        example: 123
        description: Customer Tax Number
      CustLimit:
        type: number
        format: float
        example : 1.23
        description: Credit limit
    example:
      CustKey: 123
      CustRtype: 123
      CustName: "ABC"
      CustStreet: "ABC"
      CustCity: "ABC"
      CustState: "ABC"
      CustZip: 123
      CustContact: "ABC"
      CustPhone: 123
      CustFax: 123
      CustGift: 123
      CustTcode: "ABC"
      CustTaxno: 123
      CustLimit: 1.23
  Order:
    required:
    - OrNumber
    properties:
      OrNumber:
        type: integer
        example: 123
        description: Order number
      OrVendor:
        type: integer
        example: 123
        description: Vendorcode
      OrItem:
        type: integer
        example: 123
        description: Item code
      OrCustomer:
        type: integer
        example: 123
        description: Customer number
      OrQty:
        type: integer
        example: 123
        description: Quantity on order
      OrPrice:
        type: number
        format: float
        example : 1.23
        description: Order Price
      OrTerms:
        type: string
        example: "ABC"
        description: Order Terms code
      OrOdate:
        type: string
        format: date-time
        example: 123
        description: Order date
      OrSdate:
        type: string
        format: date-time
        example: 123
        description: Req ship date
      OrEdate:
        type: string
        format: date-time
        example: 123
        description: Expiration date
      OrInvoice:
        type: integer
        example: 123
        description: Invoice Number
    example:
      OrNumber: 123
      OrVendor: 123
      OrItem: 123
      OrCustomer: 123
      OrQty: 123
      OrPrice: 1.23
      OrTerms: "ABC"
      OrOdate: 123
      OrSdate: 123
      OrEdate: 123
      OrInvoice: 123
  Plant:
    required:
    - InItemid
    properties:
      InItemid:
        type: integer
        example: 123
        description: Item ID
      InSource:
        type: integer
        example: 123
        description: Vending Source Code
      InSize:
        type: integer
        example: 123
        description: Size in gallons
      InName:
        type: string
        example: "ABC"
        description: Common name
      InLatin:
        type: string
        example: "ABC"
        description: Latin name
      InZone:
        type: integer
        example: 123
        description: Zone
      InType:
        type: integer
        example: 123
        description: Type code
      InFlower:
        type: string
        example: "ABC"
        description: Flowering?
      InColor:
        type: string
        example: "ABC"
        description: Flower color
      InShape:
        type: string
        example: "ABC"
        description: Plant shape
      InMaxhigh:
        type: integer
        example: 123
        description: Maximum height (in inches)
      InMaxwide:
        type: integer
        example: 123
        description: Maximum width (in inches)
      InWater:
        type: string
        example: "ABC"
        description: Water requirements
      InSun:
        type: string
        example: "ABC"
        description: Sun requirements
      InLocation:
        type: string
        example: "ABC"
        description: Bin/aisle
      InOnhand:
        type: integer
        example: 123
        description: Qty on hand
      InAllocated:
        type: integer
        example: 123
        description: Qty allocated
      InOnorder:
        type: integer
        example: 123
        description: Qty on order
      InMinimum:
        type: integer
        example: 123
        description: Reorder point
      InPrice:
        type: number
        format: float
        example : 1.23
        description: Unit Price
      InCost:
        type: number
        format: float
        example : 1.23
        description: Item Cost
    example:
      InItemid: 123
      InSource: 123
      InSize: 123
      InName: "ABC"
      InLatin: "ABC"
      InZone: 123
      InType: 123
      InFlower: "ABC"
      InColor: "ABC"
      InShape: "ABC"
      InMaxhigh: 123
      InMaxwide: 123
      InWater: "ABC"
      InSun: "ABC"
      InLocation: "ABC"
      InOnhand: 123
      InAllocated: 123
      InOnorder: 123
      InMinimum: 123
      InPrice: 1.23
      InCost: 1.23
  Vendor:
    required:
    - VendKey
    properties:
      VendKey:
        type: integer
        example: 123
        description: Vendor ID
      VendRtype:
        type: integer
        example: 123
        description: Record Type
      VendName:
        type: string
        example: "ABC"
        description: Vendor Name
      VendStreet:
        type: string
        example: "ABC"
        description: Street Address
      VendCity:
        type: string
        example: "ABC"
        description: City
      VendState:
        type: string
        example: "ABC"
        description: State
      VendZip:
        type: integer
        example: 123
        description: Zip Code
      VendContact:
        type: string
        example: "ABC"
        description: Contact Person
      VendTelephone:
        type: integer
        example: 123
        description: Phone number
      VendFax:
        type: integer
        example: 123
        description: Fax Number
      VendTerms:
        type: string
        example: "ABC"
        description: Terms & Conditions
    example:
      VendKey: 123
      VendRtype: 123
      VendName: "ABC"
      VendStreet: "ABC"
      VendCity: "ABC"
      VendState: "ABC"
      VendZip: 123
      VendContact: "ABC"
      VendTelephone: 123
      VendFax: 123
      VendTerms: "ABC"
